version: '3.8'
services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6379:6379'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local